# Generated by Django 2.0.6 on 2019-01-21 10:09

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=40, null=True, unique=True)),
                ('department_description', models.TextField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=40, null=True)),
                ('version', models.CharField(max_length=20, null=True)),
                ('about', tinymce.models.HTMLField(null=True, verbose_name='About')),
                ('note', models.TextField(blank=True, null=True)),
                ('modified_date_time', models.DateTimeField(auto_now=True)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('publish_mode', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=40)),
                ('project_description', models.TextField(max_length=300, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documentation.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=20, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='product', on_delete=django.db.models.deletion.CASCADE, to='documentation.Project'),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(to='documentation.Tags'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('department', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('project', 'version')},
        ),
    ]
